#!/bin/bash
cd "$(dirname "$0")"
. common/libc.sh
if [[ $# < 1 ]]; then
  echo >&2 "Usage: $0 id [name1 [name2 ...]]"
  exit 2
fi
id=$1
shift 1
if [[ $# == 0 ]]; then
  names="__libc_start_main_ret system execve dup2 open read write gets str_bin_sh __malloc_hook __free_hook __realloc_hook __after_morecore_hook stdin stdout _IO_list_all"
else
  names="$@"
fi
ls -1 "db/${id}."* >/dev/null 2>&1 || die "Invalid ID '$id'"
for name in $names; do
  offset=`cat db/${id}.symbols | grep "^$name " | cut -d' ' -f2`
  [ -z "$offset" ] && die "Invalid symbol '$name'"
  echo "offset_${name} = 0x${offset}"
done
